### ISSUE TITLE
Support having non-relative links that work for both dev and prod

### ISSUE THREAD

**Issue by catherineluse** [longhorn/website#67]
In the Rancher docs, we have this variable "baseurl" that begins every link in the docs. So our links in source code look like this:

```
{{<baseurl>}}/rancher/v2.x/en/installation/
```

In production it translates to:
```
https://rancher.com/docs/rancher/v2.x/en/installation/
```

But in the dev environment it translates to:
```
localhost:9001/rancher/v2.x/en/installation
```

It would be nice to have this variable available in the Longhorn docs because it would save me some time, when fixing broken links, to just insert the URL that I know is correct, without having to figure out where the link target is relative to the page the link is on.

But of course since this is the Longhorn docs, the prod version of baseurl would be `longhorn.io` and the dev version would be `localhost:1313`.

**Comment by yasker** [comment]
Hi @lucperkins ,

Is this something we can support within the current framework?

Thanks.

**Comment by lucperkins** [comment]
I think that this change may not be advisable for longhorn.io due to versioning. Because all docs URLs are of the form `/docs/VERSION/foo`, relative URLs enable all URLs to be version agnostic. I *could* make a shortcode that includes the versioning information, but the drawbacks would be that:

1. All existing links would need to be converted to the new system
2. Anyone who works on the docs/site would need to know how the shortcode works to contribute

I'm happy to make the shortcode (and let others convert the links) but I think those issues are worth beaing in mind.

**Comment by catherineluse** [comment]
I think Luc is right. I'll just use the VsCode extension Relative Path to make it a little easier to fix relative links. I'm going to close this issue and maybe reopen it if it looks like we still need it after the reorganization is done.
